services:
  backend_1:
    build: ./backend
    container_name: backend_1
    environment:
      - SERVER_PORT=8081
      - SERVER_MAX_HTTP_HEADER_SIZE=65536
      - SERVER_MAX_HTTP_REQUEST_HEADER_SIZE=65536
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=abc
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://lvh.me:8080/realms/docs
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/docs/protocol/openid-connect/certs
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net
      - db-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
  backend_2:
    build: ./backend
    container_name: backend_2
    environment:
      - SERVER_PORT=8081
      - SERVER_MAX_HTTP_HEADER_SIZE=65536
      - SERVER_MAX_HTTP_REQUEST_HEADER_SIZE=65536
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=abc
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://lvh.me:8080/realms/docs
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/docs/protocol/openid-connect/certs
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net
      - db-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - AUTH_SECRET=super_duper_secret
      - AUTH_TRUST_HOST=true
      - KEYCLOAK_CLIENT_ID=docs-app
      - KEYCLOAK_CLIENT_SECRET=UTRPYOFyA9CRzdW0psndgr8xCeOwvnm2
      - KEYCLOAK_ISSUER=http://lvh.me:8080/realms/docs
      - KEYCLOAK_INTERNAL_ISSUER=http://keycloak:8080/realms/docs
      - KEYCLOAK_PUBLIC_ISSUER=http://lvh.me:8080
      - AUTH_URL=http://localhost/api/auth
      - NEXTAUTH_URL=http://localhost
      - BACKEND_URL=http://nginx
      - LOCAL_IP=lvh.me
    depends_on:
      - backend_1
      - backend_2
    networks:
      - app-net
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend_1
      - backend_2
    networks:
      - app-net
  redis:
    image: redis:8
    container_name: redis
    networks:
      - app-net
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - db_username
      - db_password
    networks:
      - db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: abc
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME: lvh.me
    secrets:
      - db_username
      - db_password
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      app-net:
        aliases:
          - lvh.me
      db-net:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/127.0.0.1/9000 && echo -e 'GET /health/ready HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n' >&3 && grep 'HTTP/1.1 200 OK' <&3",
        ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  postgres-data:
  redis-data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_username:
    file: ./secrets/db_username.txt

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${APP_SUBNET}
          gateway: ${APP_GATEWAY}
  db-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${DB_SUBNET}
          gateway: ${DB_GATEWAY}
