spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doccollab
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/docs
  data:
    redis:
      host: localhost
      port: 6379