spring.application.name=backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=user
spring.datasource.password=abc
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/docs
server.max-http-request-header-size=65536
spring.data.web.pageable.page-serialization-mode=via-dto